moira-alert/moira

- Dockerfile.notifier
> Revert "Update Dockerfile.notifier"

- checker/check.go
- database/redis/database.go
removed unnecessary returns for error-type-dependent cases
log net.OpError itself
> syntax sugar

- metrics/graphite/go-metrics/init.go
- metrics/graphite/go-metrics/init_test.go
added hostname variable to metrics.prefix
> Hostname var in prefix

- .travis.yml
- cmd/checker/config.go
- cmd/config.go
- cmd/notifier/config.go
- vendor/vendor.json
- fix broken Moira builds (dep: gosexy | menteslibres.net down)
> Moira Builds

- api/controller/events.go
- api/controller/events_test.go
- api/controller/notification.go
- api/controller/notification_test.go
- api/handler/event.go
- api/handler/notification.go
- database/redis/notification.go
- database/redis/notification_event.go
- database/redis/notification_event_test.go
- database/redis/notification_test.go
- interfaces.go
- mock/moira-alert/database.go
It's designed to be placed on hidden url `<moira>/notifications` to delete all events and notifications at once.
> Added API methods deleting all notifications and all notification events

- api/controller/contact.go
- api/controller/contact_test.go
>  disallow to remove contact with assigned subscriptions found

- Makefile
see alecthomas/gometalinter#505
> Guys changed linter name here alecthomas/gometalinter#505

- filter/patterns/worker.go
> fix timer leak

- api/controller/contact.go
- api/controller/subscription.go
- api/controller/trigger.go
- api/handler/trigger.go
- checker/check.go
- checker/check_test.go
- checker/timeseries_test.go
- target/fetchdata.go
- target/fetchdata_test.go
- target/target.go
- target/target_test.go
- target/timeseries.go
- target/timeseries_test.go
- vendor/vendor.json
commit  ccac7217894801a5a6ceb8602a70ea0d79e975cf
> Update carbonapi to 1.0.0-rc.0

- checker/worker/worker.go
- cmd/checker/config.go
- cmd/filter/config.go
- cmd/filter/main.go
- pkg/filter/filter.yml
> Fix default MaxParallelMatches option. If not set or equal 0, set it to number of CPU

- datatypes.go
- datatypes_test.go
I fixed bug and made tests more clear.
> Fix complex time in schedule

- checker/check.go
- checker/check_test.go
- checker/event.go
- checker/trigger.go
- datatypes.go
Попытался сделать так, чтобы мы не падали в EXCEPTION при каждом затупе графита.
Заодно отрефакторил логику, которая приехала в #113
> Trying to make remote triggers exceptions more secure.

- api/controller/trigger.go
- api/controller/trigger_test.go
- api/handler/trigger.go
bond with moira-alert/web2.0#167
> Add new method which deletes all NODATA metrics from trigger

- Makefile
- api/dto/subscription.go
- api/handler/subscription.go
- plotting/helpers.go
- plotting/legend.go
Почему-то старый линтер немного ругался на перекрытия переменных, а новый нет. Но я поправил на всякий случай =) Вот в этом коммите https://github.com/moira-alert/moira/commit/bb38c7258f6420b612556a1a5aadc0c7096750f7
> Forbid to use other user contacts

- api/controller/trigger.go
- api/controller/trigger_test.go
- api/error.go
- api/handler/trigger.go
> Remove deprecated API-method. 

- datatypes_test.go
- notifier/scheduler.go
- notifier/scheduler_test.go
Починил баг, из-за которого не работало сложное расписание в подписках.
> Fix bug with advanced schedule in subscription

- notifier/notifier.go
- notifier/notifier_test.go
- notifier/plotting.go
- plotting/curve.go
- plotting/plot.go
- plotting/plot_test.go
> Improve metricsToShow resolving logic

- senders/slack/slack.go
> add emoji logic to slack sender

- api/controller/contact.go
- api/controller/contact_test.go
- api/controller/events_test.go
- api/controller/pattern_test.go
- api/controller/subscription.go
- api/controller/subscription_test.go
- api/controller/trigger_metrics_test.go
- api/controller/trigger_test.go
- api/controller/triggers.go
- api/controller/triggers_test.go
- api/controller/user_test.go
- database/redis/last_check_test.go
- database/redis/notification_event_test.go
- database/redis/remote_triggers_to_check_test.go
- database/redis/subscription_test.go
- database/redis/triggers_to_check_test.go
- database/redis/triggers_to_reindex_test.go
- database/redis/unused_triggers_test.go
- index/bleve/trigger_index_benchmark_test.go
- vendor/vendor.json
Repository was moved to github.com/gofrs/uuid
> go.UUID update

- database/redis/database.go
```
// Dial connects to the Redis server at the given network and
// address using the specified options.
func Dial(network, address string, options ...DialOption) (Conn, error) {
do := dialOptions{
dial: net.Dial,
}
for _, option := range options {
option.f(&do)
}
netConn, err := do.dial(network, address)
if err != nil {
return nil, err
}
if do.dialTLS {
tlsConfig := cloneTLSClientConfig(do.tlsConfig, do.skipVerify)
if tlsConfig.ServerName == "" {
host, _, err := net.SplitHostPort(address)
if err != nil {
netConn.Close()
return nil, err
}
tlsConfig.ServerName = host
}
tlsConn := tls.Client(netConn, tlsConfig)
if err := tlsConn.Handshake(); err != nil {
netConn.Close()
return nil, err
}
netConn = tlsConn
}
c := &conn{
conn:         netConn,
bw:           bufio.NewWriter(netConn),
br: …
```
> Do not select db manually

- expression/expression.go
> Replace map with cache

- database/redis/metric.go
- filter/cache_storage.go
- filter/matched_metrics/metrics.go
1. Replace time.After with Timer to reduce internal allocations of timers
2. Prefetch next batch during save of the previous
> Tiny refactoring of the filter

- index/bleve/trigger_index.go
- vendor/vendor.json
Scorch is a new index for Bleve:
https://www.youtube.com/watch?v=zjG2Y01i3Kk
> Change Bleve index-type to Scorch as it is much faster than upside_down

- filter/metrics_parser.go
- filter/metrics_parser_test.go
- filter/patterns_storage.go
- filter/patterns_storage_test.go
- helpers.go
- helpers_test.go
- unsafe.go
- unsafe_test.go
- vendor/vendor.json
> Tags support

- notifier/notifications/notifications.go
> Do not drop notifications when Notifier selfstate is not ok

- senders/pushover/pushover.go
- senders/pushover/pushover_test.go
- vendor/vendor.json
> Limit the URL and title in pushover sender

- api/controller/trigger.go
- api/controller/trigger_test.go
- api/handler/trigger.go
- checker/event.go
- checker/event_test.go
- database/redis/last_check.go
- database/redis/last_check_test.go
- datatypes.go
- datatypes_test.go
- generate_mocks.cmd
- generate_mocks.sh
- interfaces.go
- mock/moira-alert/database.go
> Add user and time on maintenance trigger

- checker/event.go
- checker/event_test.go
> revert #332

- .travis.yml
Slack: only on failures
Gitter: disable
> Reconfigure Travis build notifications

- index/bleve/trigger_index.go
- vendor/vendor.json
Revert "Change Bleve index-type to Scorch as it is much faster than upside_down (#203)"
This reverts commit ded8130000b1821fd59647837152960c63abec36.
> Revert scorch index

- .travis.yml
- Makefile
- Build packages only when tag is present
- Deploy nightly only from master
> Change deploy logic

- .travis.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.filter
- Dockerfile.notifier
- vendor/vendor.json
> Update golang and goconvey

- README.md
> Remove Gitter badge from README

- .travis.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.filter
- Dockerfile.notifier
> Bump go version

- filter/pattern_index.go
- filter/pattern_index_test.go
- filter/patterns_storage.go
https://github.com/moira-alert/moira/pull/386
> Warn if pattern or metric contain an empty part

- README.md
Added info on starting local redis for testing.
Also prettified readme a little so that it satisfies [markdownlint rules](https://github.com/DavidAnson/markdownlint/blob/v0.15.0/doc/Rules.md)
Closes #396
> Added info on local redis to dev section of readme

- notifier/notifier.go
- notifier/notifier_test.go
- notifier/registrator.go
Неожиданно поняли что легко можем распараллелить отправку сообщений одним сердером. Вове Колобаеву понравится =)
> Handle messages in one sender in parallel

- checker/check.go
- checker/check_test.go
> #355 NODATA state by TTL

- index/batch.go
- index/index_test.go
Главное что хотел сделать - более понятные ошибки при выкатывании, а то при последнем релизе было немного не понятно что происходит, заодно написал тестов и вынес красиво в функцию.
> Small refactor retries of GetTriggerChecks method

- api/controller/trigger_test.go
- database/redis/last_check.go
- database/redis/last_check_test.go
- datatypes_test.go
- senders/mail/mail.go
> formating code

- docker-compose.yml
use a discrete,named volume for redis data
> discrete data volume for redis

- filter/metrics_parser.go
- filter/metrics_parser_test.go
For more details see https://graphite.readthedocs.io/en/latest/feeding-carbon.html#step-3-understanding-the-graphite-message-format
Fixes #426
> Add support of magic "-1" metric timestamp

- .golangci.yml
- .travis.yml
- Makefile
It must resolve memory issues in Travis CI
https://github.com/golangci/golangci-lint/releases/tag/v1.20.0
> Upgrade golangci-lint to v1.21.0

- Dockerfile.cli
- Makefile
update list creation images in makefile
> Make image cli

- notifier/plotting.go
- notifier/plotting_test.go
At notifier/plotting.go inside fetchAvailableSeries in case of error
returned from `metricsSource.Fetch` only
`local.ErrEvaluateTargetFailedWithPanic` was checked. Another errors did
not handled properly and function was trying to call mehods of fetch
result which became nil. That caused Nil Pointer Dereference panic. Add
proper error handling to prevent nil pointer dereference.
Closes #437
> Fix nil pointer dereference in notifier

- cmd/cli/config.go
- cmd/cli/main.go
- cmd/cli/user.go
- cmd/cli/user_test.go
- database/redis/subscription.go
Getting a list of users through stdin
Add a whitelist of users and the delete flag (notifications and contacts for the user)
> feat: cleaning moira from fired users

- filter/patterns_storage.go
- metrics/graphite.go
- metrics/interfaces.go
- metrics/notifier.go
> Rework Counter.Inc and drop NewMetersCollection from Registry

- checker/check_test.go
- cmd/checker/main.go
- cmd/filter/main.go
- filter/cache_storage_test.go
- filter/patterns_storage_test.go
- index/index.go
- metrics/checker.go
- metrics/filter.go
- metrics/graphite.go
- metrics/index.go
- metrics/interfaces.go
- metrics/notifier.go
- notifier/registrator.go
- perfomance_tests/filter/filter_test.go
> Set up metrics prefix at start up

- api/controller/triggers.go
- api/controller/triggers_test.go
- api/dto/triggers.go
- api/handler/triggers.go
- api/middleware/context.go
- api/middleware/middleware.go
- database/redis/reply/search_result.go
- database/redis/triggers_search_results.go
- database/redis/triggers_search_results_test.go
- interfaces.go
- mock/moira-alert/database.go
Add ability to have stable pagination on GET /api/triggers/search.
Closes #457
> feat(api): Implement stable pagination

- cmd/telemetry.go
> Enable pprof heap handler

- api/handler/triggers.go
> fix(api): Handle pager params on /page url

- cmd/filter/config.go
- cmd/filter/main.go
- database/redis/contact.go
- database/redis/last_check.go
- database/redis/metric.go
- database/redis/notification_event.go
- database/redis/subscription.go
- database/redis/tag.go
- database/redis/throttling.go
- database/redis/trigger.go
- database/redis/triggers_lock.go
- filter/pattern_index.go
- filter/patterns/worker.go
- Use string contancatenation instead of Sprintf in `filter` and `database` modules
- Add a configuration parameter for filter's patterns update period
Related helmcharts PR: https://github.com/moira-alert/helmcharts/pull/5
> Filter optimizations

- go.mod
- go.sum
- mock/metric_source/fetch_result.go
- mock/metric_source/source.go
- mock/moira-alert/image_store.go
- mock/moira-alert/logger.go
- mock/moira-alert/searcher.go
- mock/moira-alert/sender.go
- mock/notifier/notifier.go
- mock/scheduler/scheduler.go
> build(mock): Update golang/mock to 1.4.1

- Makefile
- api/controller/triggers_test.go
Version updated to 1.23.8 that works correctly with go 1.14
> Update GolangCI Lint version

- filter/pattern_index.go
- filter/pattern_index_test.go
Test case is pretty self-explanatory.
> Fix pattern matching in filter

- plotting/legend.go
> fix: Metrics mixed up in graph legend

- api/handler/trigger.go
- api/middleware/context.go
- api/middleware/middleware.go
- datatypes.go
- datatypes_test.go
- notifier/notifier.go
* Add templates to trigger description
* Add presentation of trigger description in non-editing for API
Close #484
> Add templates to trigger description #484

- api/dto/triggers.go
> fix(api): Add alone metrics to get trigger reply

- api/dto/triggers.go
- checker/errors.go
- checker/errors_test.go
> fix: fix alone metrics check error message

- notifier/selfstate/selfstate_test.go
*  added more time to pass the test
> fix: test selfstate

- filter/matched_metrics/metrics.go
Fixed data type conflict in the Metrics Matcher launch information message.
Fixed blocking on completion of Moira Filter via interrupt with extra computation (Optional chan).
As a solution, a method of organizing additional calculations was used by adding a channel named closeRequest to the MetricsMatcher properties and monitoring its state in select block. When the channel is closed in a call to metricsMatcher.Wait (), MetricsMatcher exits and no blocking occurs in the select block. Thus, the service terminates gracefully.
https://github.com/moira-alert/moira/blob/9b3029b56cf0b62d7d35ebbe2e98013638099c19/filter/matched_metrics/metrics.go#L46
> fix(filter): Fixed incorrect shutdown and conflict of data types during output in MetricsMatcher.

- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
update golang to 1.14.6
Возникли проблемы при билде на моем ноутбуке, предлагаю обновить голэнг, так как 
старая версия привносит проблемы в разработку. 
https://github.com/golang/go/issues/37436
> feat: update golang

- senders/telegram/handle_message.go
- senders/telegram/handle_message_test.go
> fix(senders): Fixed Telegram group chat response message

- notifier/plotting.go
- notifier/plotting_test.go
Plots were not sent to Slack and Telegram. The problem was iterating over the keys in the map `metricsData`.
> fix(notifier): Fixed sending of plots in notifications

- senders/slack/slack.go
> fix(slack): remove "parse" post message argument

- senders/telegram/handle_message.go
- senders/telegram/handle_message_test.go
Bot sends response only if message is `/start@MoiraBot`
> Fixed Telegram group chat response message

- senders/telegram/handle_message.go
- senders/telegram/handle_message_test.go
> Respond only to messages beginning with /start in Telegram

- api/config.go
- api/dto/target.go
- api/dto/target_test.go
- api/dto/triggers.go
- api/handler/handler.go
- api/handler/trigger.go
- api/handler/triggers.go
- api/middleware/context.go
- api/middleware/middleware.go
- cmd/api/config.go
- cmd/api/main.go
> Mark all dangerous Graphite functions as such

- notifier/notifier.go
> feat(notifier): Add error logging in notifier

- notifier/notifier.go
> hotfix: clone logger

- notifier/notifier.go
> fix(notifier): Fix logging place

- go.mod
- go.sum
- senders/slack/slack.go
- senders/slack/slack_test.go
> Slack client updated

- notifier/plotting.go
> Notifier: excluded logs if plots disabled

- database/redis/teams.go
- database/redis/teams_test.go
Implement realisation for methods of database interface that manipulated with teams
Relates #230
> Implement teams database methods

- api/handler/triggers.go
Changed trigger check http-method to PUT for transfer params via body
Related with web [fix](https://github.com/moira-alert/web2.0/pull/343).
> fix: changed trigger/check method to PUT and body params

- templating/templating.go
- templating/templating_test.go
Web2.0 changes here https://github.com/moira-alert/web2.0/pull/349
TODO: add to docs
> add strings methods to templating functions

- checker/check_test.go
> fix(checker): Fix prepare test

- database/redis/contact.go
- database/redis/database.go
There were two problems in `GetContacts`:
1. used `Keys` command that [not recommended](https://redis.io/commands/KEYS) to use in production
2. keys searched for only on one node (which, in the case of a cluster, led to incorrect results)
Also, improved the `flush` method to work on the Redis cluster correctly.
> Fixed contacts on redis cluster

- database/redis/bot_test.go
- database/redis/contact.go
- database/redis/contact_test.go
- database/redis/database.go
- database/redis/database_test.go
- database/redis/last_check_test.go
- database/redis/locks_test.go
- database/redis/metric_test.go
- database/redis/notification_event_test.go
- database/redis/notification_test.go
- database/redis/selfstate_test.go
- database/redis/subscription_test.go
- database/redis/tag_test.go
- database/redis/teams_test.go
- database/redis/throttling_test.go
- database/redis/trigger_test.go
- database/redis/triggers_lock_test.go
- database/redis/triggers_search_results_test.go
- database/redis/triggers_to_check_test.go
- database/redis/triggers_to_reindex_test.go
- database/redis/unused_triggers_test.go
There were two places where you needed to change the connection string to the test database. It was not very elegant.
> Removed unnecessary newTestDatabase function

- cmd/cli/extra.go
- cmd/cli/extra_test.go
- cmd/cli/main.go
1. compile cli
```bash
$ go build -o build/cli github.com/moira-alert/moira/cmd/cli
```
2. run command
```bash
$ ./build/cli --config local/cli.yml -make-all-triggers-datasource-local
```
> Added command to make all triggers datasource local

- .github/workflows/codeql-analysis.yml
- .run/run moira.run.xml
- .run/run redis.run.xml
- checker/worker/worker.go
- cmd/cli/user.go
- cmd/cli/user_test.go
More information about [CodeQL](https://codeql.github.com)
Related to https://github.com/moira-alert/moira/pull/557
> Added CodeQL analysis

- database/redis/contact.go
before:
> GET http://127.0.0.1:8080/api/contact HTTP/1.1 from 127.0.0.1:39580 by anonymous - 200 155663B in **1m53.036403899s**
after:
> GET http://127.0.0.1:8080/api/contact HTTP/1.1 from 127.0.0.1:39580 by anonymous - 200 155663B in **2.671802051s**
> Improved GetAllContacts method

- .github/workflows/test.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
- go.mod
https://github.com/moira-alert/moira/pull/642 was taken as an example
> Updated golang to 1.17.7

- senders/pagerduty/send.go
- senders/pagerduty/send_test.go
> Added PagerDuty multiple plots support

- filter/series_by_tag.go
- filter/series_by_tag_pattern_index_test.go
Wildcards like `responseCode={405,406,407,411,413,414,415}` were processed incorrectly before. This PR fixes this problem.
> Added wildcard support to SeriesByTag target

- cmd/cli/main.go
- cmd/cli/metrics.go
- database/redis/metric.go
- database/redis/metric_test.go
- interfaces.go
- mock/moira-alert/database.go
1. compile cli
```bash
$ go build -o build/cli github.com/moira-alert/moira/cmd/cli
```
2. run command to remove metrics by pattern
```bash
$ ./build/cli --config local/cli.yml -remove-metrics-by-prefix "k8s.dev-cl1."
```
3. run command to remove ALL metrics
```bash
$ ./build/cli --config local/cli.yml -remove-all-metrics
```
> Added command to remove metrics by prefix

- filter/metrics_parser.go
- filter/metrics_parser_test.go
WARNING: You should remove all metrics in database first
```
./build/cli --config local/cli.yml -remove-all-metrics
```
> Added sorting labels of tagged metrics

- cmd/api/config.go
- cmd/config.go
- database/redis/config.go
- database/redis/database.go
Added availability to set max_retries attribute: default value 3
> Added availability to set max_retries attribute

- filter/config.go
> Deleted unused file

- metric_source/local/local.go
- metric_source/local/local_test.go
If there is no data for metric, carbonapi consider it error `parser.ErrSeriesDoesNotExist`, but for Moira it is ok! It can happen when Graphite stopped or Moira clients send events instead of metrics.
There was wrapped error `parser.ErrSeriesDoesNotExist` that we don't handle, so some triggers gone in Exception state on cleanup of cli. Added handle.
> Fixed error handle

- api/dto/target.go
- api/dto/target_test.go
There is a bug - can't create trigger with target with only series (without Graphite-function). Need to test method TargetVerification in current state, then add test to reproduce that bug and fix it.
> Add functional of creating trigger with target with flat metric

- .github/workflows/lint.yml
- .golangci.yml
- api/controller/team.go
- api/controller/trigger.go
- checker/check_test.go
- checker/metrics/conversion/alone_metrics.go
- checker/metrics/conversion/trigger_metrics.go
- cmd/config.go
- database/redis/reply/check.go
- errors.go
- helpers.go
- index/triggers.go
- metric_source/remote/request.go
- plotting/fonts/ttftogofile/ttf2gofile.go
- plotting/legend.go
- plotting/themes/dark/dark.go
- plotting/themes/light/light.go
- senders/msteams/datatypes.go
- senders/msteams/msteams.go
- senders/victorops/api/alert.go
- senders/webhook/webhook.go
- state.go
- unsafe.go
Updated golangci version. And delete unused linters
> Update golangci to v1.50.1

- checker/config.go
- checker/worker/metrics.go
- checker/worker/worker.go
- cmd/checker/config.go
- database/redis/database.go
- database/redis/metric.go
- database/redis/metric_test.go
- datatypes.go
- interfaces.go
- mock/moira-alert/database.go
- pkg/checker/checker.yml
Ticket brings an ability to launch more than one checker
> n checkers

- notifier/events/event.go
- notifier/events/event_test.go
- notifier/log_common.go
- notifier/notifications/notifications.go
- notifier/notifier.go
- notifier/plotting.go
- notifier/registrator.go
- notifier/scheduler.go
- notifier/selfstate/check.go
- notifier/selfstate/heartbeat/database.go
- notifier/selfstate/heartbeat/filter.go
- notifier/selfstate/heartbeat/heartbeat.go
- notifier/selfstate/heartbeat/local_checker.go
- notifier/selfstate/heartbeat/notifier.go
- notifier/selfstate/heartbeat/remote_checker.go
- notifier/selfstate/selfstate.go
- worker/worker.go
Rewrite logs in `notifier`, `worker` packages to new format with features form [this PR](https://github.com/moira-alert/moira/pull/811).
> feat(logging) Rewrite logs in notifier, worker

- api/controller/pattern.go
- api/controller/tag.go
- api/handler/trigger.go
- api/handler/triggers.go
- api/middleware/logger.go
- cmd/api/main.go
- cmd/checker/config.go
- cmd/checker/main.go
- cmd/cli/extra.go
- cmd/cli/main.go
- cmd/cli/triggers.go
- cmd/cli/user.go
- cmd/filter/main.go
- cmd/image_store.go
- cmd/notifier/config.go
- cmd/notifier/main.go
- cmd/telemetry.go
- log_fields.go
- notifier/notifier.go
Rewrite logs in api, database and cmd packages to new format with features from [this PR](https://github.com/moira-alert/moira/pull/811).
> feat(logging) Rewrite logging for sentry api, database, cmd

- notifier/events/event.go
when errors were happen we didn't have enough info about it
> Add more logs in notifier

- go.mod
- go.sum
- senders/slack/slack.go
in old methods slack stopped sending in threads
> Fix sending plot in slack-threads

- .github/workflows/lint.yml
- metrics/notifier.go
- metrics/prometheus.go
- notifier/plotting.go
- notifier/scheduler.go
we need some metric to track how long we draws plots
> Add metrics for plotting

- cmd/config.go
- database/redis/config.go
- database/redis/database.go
Added new configuration option sentinel_pass and passed it to redis library.
> Add support for sentinel auth

- cmd/cli/main.go
- cmd/cli/triggers.go
- cmd/cli/triggers_test.go
i added new func for delete triggers without subscriptions and id has been started with "smth"
> add func to delete unused triggers without subscriptions

- cmd/cli/from_2.7_to_2.8.go
- cmd/cli/main.go
- database/redis/contact.go
Cannot use unknown user -  when we fix returned param in this PR
https://github.com/moira-alert/moira/pull/824/files#diff-de5e720e63d164ed6aac743fefb2d810c42f992373004d4f65ef57a5c82c3ab3R50
> Add func to up from 2.7 to 2.8

- .github/workflows/docker-release.yml
Fix incorrect docker tag for releases images
> Fix docker-release action

- api/config.go
- cmd/api/config.go
- cmd/api/config_test.go
- local/api.yml
- pkg/api/api.yml
added info /api/config feature-flags config to do any manipulations on frontend
> add feature-flag into /config

- expression/expression.go
- expression/expression_test.go
Also added two validation tests
> fix(expression): add vars validation for trigger

- datatypes.go
- datatypes_test.go
- notifier/events/event.go
- notifier/events/event_test.go
- senders/discord/send.go
- senders/mail/send.go
- senders/mattermost/sender.go
- senders/msteams/msteams.go
- senders/opsgenie/send.go
- senders/pagerduty/send.go
- senders/pushover/pushover.go
- senders/slack/slack.go
- senders/telegram/send.go
- senders/twilio/sms.go
- senders/victorops/send.go
Refactored the GetMetricsValues function to be able to reduce the message length
> fix(senders): fix text in sms and email

- datatypes.go
- datatypes_test.go
- senders/discord/send.go
- senders/mail/send.go
- senders/mattermost/sender.go
- senders/msteams/msteams.go
- senders/opsgenie/send.go
- senders/opsgenie/send_test.go
- senders/pagerduty/send.go
- senders/pushover/pushover.go
- senders/pushover/pushover_test.go
- senders/selfstate/selfstate.go
- senders/slack/slack.go
- senders/telegram/send.go
- senders/twilio/sms.go
- senders/victorops/send.go
- senders/victorops/send_test.go
- state.go
Also fixed the corresponding tests
> fix(senders): fixed trigger going to wrong final state when trottling

- api/controller/triggers.go
- api/controller/triggers_test.go
Also fixed corresponding tests
> fix(api): add correct handling of trigger id in url

- senders/telegram/handle_message.go
- senders/telegram/init.go
> fix(senders): fix error validation in telegram

- mock/notifier/mattermost/client.go
- senders/mattermost/client.go
- senders/mattermost/sender.go
- senders/mattermost/sender_internal_test.go
Fixed sending Plot in Mattermost sender.
> fix(notifier|mattermost) added plot sending

- cmd/notifier/config.go
- metrics/checker.go
- notifier/config.go
- notifier/notifier.go
Make error logs only if more than XX-unsuccessfully count to send alert
> make not noisy logs

- database/redis/contact.go
- helpers.go
and no panic anymore in key[14:] calls
> little fix in contact anf helpers

- api/controller/triggers.go
- api/controller/triggers_test.go
- api/handler/triggers.go
for getting triggers without subs
> add api for get unused triggers

- senders/discord/init.go
- senders/mail/mail.go
- senders/mattermost/sender.go
- senders/mattermost/sender_internal_test.go
- senders/mattermost/sender_test.go
- senders/msteams/msteams.go
- senders/msteams/msteams_test.go
- senders/opsgenie/init.go
- senders/pagerduty/init.go
- senders/pushover/pushover.go
- senders/script/script.go
- senders/slack/slack.go
- senders/slack/slack_test.go
- senders/telegram/init.go
- senders/twilio/twilio.go
- senders/twilio/twilio_test.go
- senders/victorops/init.go
- senders/webhook/webhook.go
> fix(senders): fix mapstructure types

- cmd/cli/main.go
Closes #[issue](https://github.com/moira-alert/moira/issues/917)
> fix validation when upgrade 2.7->2.8

- cmd/filter/compatibility.go
- cmd/filter/config.go
- cmd/filter/main.go
- filter/compatibility.go
- filter/pattern_index.go
- filter/pattern_index_test.go
- filter/patterns_storage.go
- filter/patterns_storage_test.go
- filter/series_by_tag.go
- filter/series_by_tag_pattern_index.go
- filter/series_by_tag_pattern_index_test.go
- perfomance_tests/filter/performance_test_utils.go
> feat(filter): loose tag regex and compatibility

- .github/workflows/lint.yml
- .golangci.yml
- cmd/notifier/config.go
- database/redis/metric.go
- metrics/graphite.go
- notifier/plotting.go
- perfomance_tests/filter/performance_test_utils.go
upgrade linter version and add more linters
> fix(build): upgrade linter version

- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
- go.mod
> build(go): update go to 1.19

- api/handler/contact.go
- api/handler/contact_test.go
- database/redis/reply/metric.go
It seems that when creating the method they simply forgot to put in the required parameter. Also added tests
> fix(api): fix remove contact in teams

- api/handler/config.go
> fix(api): fix config example

- filter/metrics_parser_test.go
- go.mod
- go.sum
- metric_source/local/eval.go
- metric_source/local/local_test.go
Update to the latest carbonapi.
Include some fixes: (transformNull, curentAbove, etc)
> fix(cheker,api,notifier): update carbonapi to v0.16.2-0

- cmd/notifier/config.go
- database/redis/database.go
- database/redis/metric.go
- local/notifier.yml
> fix(notifier): reduce transaction timeout and returned random seed

- api/config.go
- cmd/api/config.go
- cmd/api/config_test.go
> feat(api): add platform field to get sentry handler

- api/controller/trigger.go
- api/controller/trigger_metrics_test.go
- api/controller/trigger_test.go
- api/controller/triggers_test.go
- database/redis/triggers_lock.go
> increase sleep and attempts count for lock

- checker/check.go
- checker/check_test.go
> fix(checker): fix high memory usage in checker

- api/controller/tag.go
- api/controller/tag_test.go
- api/dto/tag.go
- api/handler/contact_test.go
- api/handler/tag.go
- api/handler/tag_test.go
- api/handler/trigger_test.go
- api/middleware/logger.go
- database/redis/tag.go
- database/redis/tag_test.go
- go.mod
- interfaces.go
- mock/moira-alert/database.go
Added a new api for adding an array of tags. Also added tests for handler tags
> feat(api): add create tags api route

- api/config.go
- api/controller/contact.go
- api/controller/contact_test.go
- api/controller/subscription.go
- api/controller/subscription_test.go
- api/controller/team.go
- api/controller/team_test.go
- api/dto/target.go
- api/handler/contact.go
- api/handler/handler.go
- api/handler/health.go
- api/handler/health_test.go
- api/handler/notification.go
- api/handler/pattern.go
- api/handler/subscription.go
- api/handler/team.go
- api/middleware/authorization.go
- api/middleware/context.go
- api/middleware/middleware.go
- cmd/api/config.go
- cmd/api/config_test.go
Add simple parameter to limit non-admin users and give additional privileges to admins
> Add admin permissions via list of admins in api

- api/controller/subscription.go
- api/handler/subscription.go
Add handler in api to get single subsription by id. Only user with rights for subscription cah use this handler, others will get 403 Forbidden
> feat(api): Add api for getting a single subscription

- go.mod
- go.sum
- senders/discord/init.go
- senders/slack/slack_test.go
- unsafe.go
> feat: Update go to 1.21

- filter/cache_storage.go
- filter/connection/listening.go
- filter/heartbeat/worker.go
- filter/metrics_parser.go
- filter/patterns_storage.go
- filter/prefix_tree.go
- filter/series_by_tag.go
- filter/series_by_tag_pattern_index.go
Changed the logging level for some logs
> fix(filter): fix filter logs

- cmd/cli/main.go
- cmd/cli/metrics.go
- database/redis/metric.go
- database/redis/metric_test.go
- database/redis/notification.go
- interfaces.go
- mock/moira-alert/database.go
Added a command to cli to remove outdated pattern metrics
Closes #921
> feat(cli): add clean up moira pattern metrics key

- filter/matched_metrics/metrics.go
Change time.Second for batchForcedSaveTime parameter in second place
> hotfix(filter): Fix batch forced save time

- cmd/config.go
- database/redis/config.go
- database/redis/database.go
Add redis config param for reading from slave nodes
> Read from slaves in redis cluster

- database/redis/metric.go
- database/redis/metric_test.go
This reverts commit 3cda2e57679e92dedc0feb9f028a80839ac201bb.
> Revert "perf(checker): add fetching metrics values in pipe (#1029)"

- api/authorization.go
- api/config.go
- api/controller/user.go
- api/controller/user_test.go
- api/dto/user.go
- api/handler/user.go
Now information about user authorization can be fetched via `/api/user` handler
> Add user authorization info to user api

- checker/check.go
Don't rewrite error while compare trigger states
> fix(checker): Don't rewrite error while compare trigger states

- checker/check.go
fix(checker): Added into checker more info about trigger
> fix(checker): Added into checker more info about trigger

- notifier/notifier.go
> hotfix(notifier): check for adding vals to log

- cmd/config.go
- cmd/config_test.go
In PR #846, authorization via Sentinel was broken
In this PR, I'm fixing the issue and doing a test to catch a similar problem in the future
> fix(config): redis sentinel

- cmd/config.go
- cmd/config_test.go
> fix(config): redis sentinel in v2.8

- .github/workflows/publish-packages.yml
> up version ruby

- .github/workflows/codeql-analysis.yml
> feat(build): Upgrade codeql

- .github/workflows/publish-packages.yml
- cmd/config.go
- cmd/config_test.go
> fix(config): redis sentinel in v2.9

- cmd/config.go
- cmd/config_test.go
> fix(config): redis sentinel in v2.10

- cmd/config.go
- cmd/config_test.go
> fix(config): redis sentinel in v2.11

- cmd/config.go
- cmd/config_test.go
> fix(config): redis sentinel in v2.12

- .github/workflows/codeql-analysis.yml
> hotfix(codeql): Remove cronjob trigger

- api/handler/subscription.go
For swagger added description for 404 error in subs.
> docs(api): add desc for 404 error in subs

- .github/workflows/swagger-delete.yml
- .github/workflows/swagger-publish.yml
before: push file only on branches
after: push file on tags 
and update actions upload/download
> fix(swagger): fix upload swagger file into swaggerhub

- .github/workflows/lint.yml
- .golangci.yml
- api/dto/team_test.go
- api/dto/triggers_test.go
- api/handler/trigger_test.go
- api/handler/triggers_test.go
- cmd/cli/main.go
- interfaces.go
- logging/zerolog_adapter/logger.go
- plotting/helpers.go
- senders/discord/init_test.go
Linters was updated. See more [here](https://golangci-lint.run/product/migration-guide/#linters).
In this PR i upgraded version and make some fix.
> feat(linter): Upgrade linter into v2.0.2

- .golangci.yml
- metric_source/local/errors.go
- metric_source/local/eval.go
- metric_source/local/fetchdata.go
- metric_source/local/fetchdata_test.go
- metric_source/local/local.go
- metric_source/local/local_test.go
- metric_source/local/timer.go
- metric_source/metric_data.go
- metric_source/metric_data_test.go
- metric_source/prometheus/convert.go
- metric_source/prometheus/fetch.go
- metric_source/prometheus/prometheus.go
- metric_source/provider.go
- metric_source/remote/remote.go
- metric_source/remote/remote_test.go
- metric_source/remote/request_test.go
- metric_source/remote/response.go
- metric_source/remote/response_test.go
- metric_source/retries/backoff_factory_test.go
- metrics/composite.go
- metrics/graphite.go
- metrics/interfaces.go
- metrics/prometheus.go
Add wsl linter into metric_source|metrics
> feat(linter): Add wsl linter into metric_source|metrics

- .golangci.yml
- integration_tests/notifier/notifier_test.go
- notifier/events/event.go
- notifier/events/event_test.go
- notifier/notifications/notifications.go
- notifier/notifications/notifications_test.go
- notifier/notifier.go
- notifier/notifier_test.go
- notifier/plotting.go
- notifier/plotting_test.go
- notifier/registrator.go
- notifier/registrator_test.go
- notifier/scheduler.go
- notifier/scheduler_test.go
- notifier/selfstate/check.go
- notifier/selfstate/check_test.go
- notifier/selfstate/config.go
- notifier/selfstate/selfstate.go
- notifier/selfstate/selfstate_test.go
> feat(linter): Add wsl linter into notifier

- .golangci.yml
- notifier/registrator.go
Removed a dot, that breaks a build.
Also fix linter
> fix(notifier): fix build

- generate_mocks.sh
- mock/clock/clock.go
- mock/heartbeat/heartbeat.go
- mock/metric_source/fetch_result.go
- mock/metric_source/source.go
- mock/moira-alert/database.go
- mock/moira-alert/database_stats.go
- mock/moira-alert/delivery_checker_database.go
- mock/moira-alert/event_builder.go
- mock/moira-alert/image_store.go
- mock/moira-alert/locks.go
- mock/moira-alert/logger.go
- mock/moira-alert/metrics/meter.go
- mock/moira-alert/metrics/meters_collection.go
- mock/moira-alert/metrics/registry.go
- mock/moira-alert/mutex.go
- mock/moira-alert/prometheus_api.go
- mock/moira-alert/searcher.go
- mock/moira-alert/sender.go
- mock/notifier/delivery/check.go
- mock/notifier/mattermost/client.go
- mock/notifier/notifier.go
- mock/notifier/telegram/bot.go
- mock/scheduler/scheduler.go
Updated mockgen in moira  from version v0.4.0 to v0.5.1
> chore: Update mockgen to v0.5.1

- api/authorization.go
- api/dto/triggers.go
- api/dto/triggers_test.go
- api/handler/trigger.go
- api/handler/triggers_test.go
- cmd/api/config.go
- cmd/api/config_test.go
If we added by list username or service-login, triggers, that be created by these login can be deleted/edited only by admins or this person.
> feat(api): Add ability filer who can change triggers

- .github/workflows/swagger-publish.yml
[see here](https://github.com/moira-alert/moira/pull/1191/files#diff-10a64f3604a7b9d642f35d38d93e6809957133becf4ff18b3eea2bed28ebaf7aR12)
> fix(swagger): Fix actions dependency

- api/config.go
- cmd/api/config.go
- cmd/api/config_test.go
- cmd/api/main.go
Need to pass metric TTL to web config to determine a valid timestamp of plot render
> feat: metric ttl to web config

- .golangci.yml
- api/controller/contact.go
- api/controller/trigger_test.go
- checker/check_test.go
- cmd/notifier/config.go
- database/redis/notification_test.go
- filter/cache_storage.go
- helpers.go
- index/fixtures/fixtures.go
- notifier/selfstate/heartbeat/filter.go
- perfomance_tests/filter/filter_plain_metrics_test.go
- perfomance_tests/filter/filter_tagged_metrics_test.go
- plotting/fonts/ttftogofile/ttf2gofile.go
- plotting/plot_test.go
- plotting/threshold_test.go
- senders/discord/send.go
- senders/msgformat/highlighter.go
- senders/opsgenie/send.go
- senders/telegram/emoji_provider.go
- senders/telegram/init.go
- senders/telegram/send.go
- senders/victorops/send.go
> feat(linter): Add staticcheck linter

- .golangci.yml
- checker/event.go
- database/redis/trigger_test.go
- senders/read_image_store_config.go
- senders/telegram/message_formatter.go
> feat(linter) Add wastedesign linter

- senders/telegram/init.go
Добавлена возожность настройки httpp прокси для сендера telegram
Closes/Relates #1202
> add proxy for telegram sender

- Dockerfile.api
- Makefile
- api/handler/triggers.go
add 
style: deepObject
explode: true
for swagger api 
make it twice:
first: in comments, if we will generate not swag
second: in make file and docker-file
> feat(swagger) Add crutch into swagger spec

- database/redis/contact.go
- database/redis/contact_test.go
- datatypes.go
- helpers.go
- helpers_test.go
- interfaces.go
- mock/moira-alert/database.go
- notifier/notifier.go
- notifier/notifier_test.go
Notifier's methods to persist contact score.
> feat: contact score notifier

- database/redis/reply/notifier.go
- database/redis/selfstate.go
- database/redis/selfstate_test.go
- docker-compose.yml
- integration_tests/notifier/notifier_test.go
- interfaces.go
- mock/moira-alert/database.go
- notifier/alive_watcher.go
- notifier/alive_watcher_test.go
- notifier/notifications/notifications.go
- notifier/notifications/notifications_test.go
- notifier/selfstate/check.go
- notifier/selfstate/check_test.go
- notifier/selfstate/heartbeat/notifier.go
- notifier/selfstate/heartbeat/notifier_test.go
- notifier/selfstate/selfstate_test.go
- senders/selfstate/selfstate.go
- senders/selfstate/selfstate_test.go
Добавил апишку для изменения состояния по отдельным источникам метрик. Добавил в нотифаер отключение отправки уведомлений в случае перехода состояния соответствующего источника в "ERROR"
- [ПР](https://github.com/moira-alert/moira/pull/1219) с новыми хэндлерами в апишке 
- [ПР](https://github.com/moira-alert/moira/pull/1221) с переделкой тестов на `testify`
> feat: Disable notifications by source in api

- api/handler/notification.go
- api/handler/triggers.go
... so that automaticaly generated clients won't struggle with our api
> Feat: Support alternative query param list parsing
