moira-alert/moira

- senders/slack/slack.go
> set markdown for slack messages

- database/redis/metric.go
- filter/connection/listening.go
Large unnecessary transaction in GetMetricValues can hang redis for some time and slowing other related services (api, filter, etc). 
Also metric queue size is configurable now.
> remove unnecessary exec & make metric queue size configurable

- senders/mail/mail.go
Email is HTML-formatted, so it ignores `\n` line breaks. To solve this, I format trigger description in this way:
- Escape all unsafe symbols, so nothing dangerous can be in resulting HTML file.
- Replace all `\n` with `\n<br/>`, so it is properly formatted HTML line breaks.
> Add multi-line formatting for email messages. Closes #16

- api/handler/trigger.go
Sometimes metric name can be blank, so empty string check is redundant.
Moira doesn't have to throw error when metric name is empty.
> Remove empty string check as metric name can be blank.

- api/controller/trigger.go
- api/controller/trigger_test.go
- checker/check.go
- checker/check_test.go
- checker/state.go
- checker/trigger_test.go
When you create a new trigger, switch its state as `TTLState` looks like a great idea. `TTLState` is an option which defines which state to set on trigger when no data provided. So, if you want to treat `NODATA` as `OK` its quite obvious to create trigger in `OK` state.
The second part is checking trigger without any metric inside. I think, we should set `TTLState` in this case too.
> Change default trigger state to TTLState

- checker/check.go
- checker/check_test.go
- checker/timeseries.go
- checker/timeseries_test.go
Improvements for ErrWrongTriggerTarget and checker.getTimeSeries show all invalid targets
Master behavior:
Branch-specific behavior:
> ErrWrongTriggerTarget -> ErrWrongTriggerTargets

- cmd/api/config.go
- cmd/checker/config.go
- cmd/config.go
- cmd/filter/config.go
- cmd/filter/main.go
- cmd/notifier/config.go
- filter/matched_metrics/metrics.go
- pkg/filter/filter.yml
added field:
- cache_capacity to make it tunable for large production solutions
changed field:
- retention-config -> retention_config (to have common underscore style for config params)
doc pr: https://github.com/moira-alert/doc/pull/21
> make filter cache capacity configurable

- api/controller/health.go
- api/controller/health_test.go
- api/dto/health.go
- api/handler/handler.go
- api/handler/health.go
- database/redis/selfstate.go
- database/redis/selfstate_test.go
- interfaces.go
- mock/moira-alert/database.go
- notifier/notifications/notifications.go
- notifier/notifications/notifications_test.go
- notifier/selfstate/health.go
- notifier/selfstate/selfstate.go
- notifier/selfstate/selfstate_test.go
Сделал MVP.
Логика такая:
- Если фильтр не принимает новых метрик или чекер ничего не проверяет, то выставляем флаг в редисе
- Флаг можно поменять через API.
- Обратно флаг выставляется только вручную через API.
> [feature] Better NODATA protection

- checker/worker/worker.go
- cmd/filter/config.go
- cmd/filter/main.go
- filter/connection/handler.go
- filter/connection/listening.go
- filter/matched_metrics/metrics.go
- filter/patterns/matcher.go
- metrics/graphite/filter.go
- metrics/graphite/go-metrics/configuration.go
We have encountered a performance issues with moira-filter (slow metrics ingestion which resulted in false-positive NODATA alerts)
The problem is that we have a large number of incoming metrics from a single host (carbon-c-relay in our case).
Current implementation assigns single goroutine per connections for a relatively slow process of pattern matching.
By introducing separate pool of pattern matching workers we completely solved our problem with slow ingestion
> Add pattern matching workers

- checker/check.go
- checker/check_test.go
- since now we don't want to notify user if something goes wrong. So, I remove checkData.State = EXCEPTION
- if there are 0 metrics in trigger, we want to switch trigger in TTLState instead of NODATA
> Few fixes of checking exceptions

- api/dto/triggers.go
- checker/check.go
- checker/check_test.go
- checker/trigger_test.go
- database/redis/reply/trigger.go
- datatypes.go
- datatypes_test.go
This PR reverse default behavior of Moira when new metrics are received. It is almost the same as #113 but by default Moira will send `NODATA - OK` events.
> The same logic as in #113, but reversed

- notifier/notifications/error.go
- notifier/notifications/notifications.go
При отключении нотифаера, мы логгируем его состояние по тикеру каждую секунду. Это бессмысленно. Сделал так, чтобы при отключении нотифаера, писалось меньше логов.
> Log notifier state every 30 seconds, not every 1 second

- api/controller/triggers_test.go
- checker/worker/nodata.go
- cmd/cli/main.go
- database/redis/database_test.go
- database/redis/trigger.go
- database/redis/trigger_test.go
- interfaces.go
- mock/moira-alert/database.go
Решил немного go вспомнить. Я тут спалил что в SaveTrigger нам никто не запрещает remote передавать триггеры с паттернами, если такое произойдет, то у нас добавятся паттерны в лист для построения дерева в фильтре. Хочется такого избежать. 
Сейчас единственное место сохранения триггера это апи, где мы по хардкору не заполняем паттерны если это не нужно, хочется уберечь себя от случайного выстрела в ногу, если мы где-то объебемся. Плюс немного переименования =)
> Never save patterns for remote triggers

- senders/slack/slack.go
fixed incorrect behavior of slack bot when sending to private chats to post as moira bot user instead of slack bot user
> fix slack bot postMessageParameters

- api/controller/trigger_metrics.go
- api/controller/trigger_metrics_test.go
- api/handler/trigger_render.go
- datatypes.go
- notifier/notifier_test.go
- notifier/plotting.go
- senders/telegram/send.go
- target/target.go
- target/target_test.go
- Retry to render plots in notifications without realtime, return ErrFetchAvailableSeriesFailed if failed again
- Added boolean ```realtime``` param to api/trigger/triggerId/render requests handler, defaults to false
- Rendering /api/trigger/triggerId/metrics allways usese AllowRealtimeAlerting set to false
- Added some more tests
> Improvements in plotting render calls

- notifier/notifier.go
- notifier/plotting.go
Эта штука засирает весь наш лог, хотя вроде это довольно обычная ситуация. Например: первый эвент.
> Ignore err no points to render

- checker/worker/lazy_triggers.go
- checker/worker/metrics.go
- checker/worker/worker.go
- filter/patterns_storage.go
- perfomance_tests/filter/filter_test.go
https://golang.org/ref/mem#tmp_10
>Another incorrect idiom is busy waiting for a value, as in:
```
var a string
var done bool
func setup() {
a = "hello, world"
done = true
}
func main() {
go setup()
for !done {
}
print(a)
}
```
>As before, there is no guarantee that, in main, observing the write to done implies observing the write to a, so this program could print an empty string too. Worse, there is no guarantee that the write to done will ever be observed by main, since there are no synchronization events between the two threads. The loop in main is not guaranteed to finish.
> Fix access to map from multiple goroutines

- filter/patterns_storage.go
- filter/patterns_storage_test.go
```
package main
import (
"bytes"
"fmt"
"math"
"strconv"
"unicode"
"unsafe"
)
func ParseMetricBase(input []byte) ([]byte, float64, int64, error) {
var parts [3][]byte
partIndex := 0
partOffset := 0
for i, b := range input {
r := rune(b)
if r > unicode.MaxASCII || !strconv.IsPrint(r) {
return nil, 0, 0, fmt.Errorf("non-ascii or non-printable chars in metric name: '%s'", input)
}
if b == ' ' {
parts[partIndex] = input[partOffset:i]
partOffset = i + 1
partIndex++
}
if partIndex > 2 {
return nil, 0, 0, fmt.Errorf("too many space-separated items: '%s'", input)
}
}
if partIndex < 2 {
return nil, 0, 0, fmt.Errorf("too few space-separated items: '%s'", input)
}
parts[partIndex] = input[partOffset:]
metric := parts[0]
if len(metric) < 1 {
return nil, 0, 0, fmt.Errorf("metric name is empty: '%s'", …
```
> Metrics parsing optimization

- senders/slack/slack.go
- senders/slack/slack_test.go
Fix #255
Solution is based on Telegram's sender.
Even though the original issue mentioned a 40k character limit, the current limit set by Slack seems to be at 4k.
> Limit message size in Slack sender

- senders/mail/mail.go
- senders/mail/send.go
Closes #289
The default LocalName (the hostname sent to the SMTP server with the HELO command) in the Dialer struct is "localhost". Therefore if the `smtp_hello` parameter is not provided, `sender.SMTPHello` is set to `""`, which then falls back to the default LocalName: https://github.com/go-gomail/gomail/blob/81ebce5c23dfd25c6c67194b37d3dd3f338c98b1/smtp.go#L75-L79
> Add smtp_hello parameter on mail sender

- pkg/api/web.json
Изменит контракт описания контактов в конфиге, потому что теперь на его основе рисуется интерфейс в настройках веб-морды Мойры.
> Change contract for config contact

- .travis.yml
- Makefile
- do not build "latest" images
- do not store unstable images in main repo, use serviceName-unstable instead (ex.: https://hub.docker.com/r/moira/checker-unstable)
> Change deploy logic

- checker/check.go
- checker/event.go
- checker/event_test.go
- cmd/api/main.go
- cmd/notifier/main.go
Don't remove maintenance info after every check process. Make logic more transparent.
Use maximal maintenance for calculating is metric in maintenance while processing new state.
Don't send "This metric changed its state" message if a state does not change during maintenance interval. Fix #328
> Generate event bug fixes

- checker/event.go
- checker/event_test.go
If metric in maintenance and change its state from initial suppress state, then event timestamp will change in every trigger check. Example:
*12:50* - Metric OK							-> In web, last Event is 10:00. **Good**
*12:51* - Set maintenance to metric
*12:53* - Trigger check with this metric.   -> In web, last Event is 10:00. **Good**
*12:55* - Metric change his state to ERROR. -> In web, last Event is 12:55. **Good**
*12:56* - Trigger check with this metric.   -> In web, last Event is 12:56. **BUG**
*12:57* - Trigger check with this metric.   -> In web, last Event is 12:57. **BUG**
*12:58* - Trigger check with this metric.   -> In web, last Event is 12:57. **BUG**
> Fix update event timestamp on maintenance metric in changed suppressed state on every trigger check

- .dockerignore
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.filter
- Dockerfile.notifier
The same technique is described [here](https://medium.com/@aidobreen/using-docker-dont-forget-to-use-build-caching-6e2b4f43771e).
> Create separate layer for installed govendor and run govendor sync only if vendors.json has changed

- README.md
- docker-compose.yml
- local/api.yml
- local/checker.yml
- local/cli.yml
- local/filter.yml
- local/nginx.conf
- local/notifier.yml
- local/relay.conf
- local/web.json
The goal of the PR is to run Moira(from source) and its environment locally:
1. Redis
2. Graphite
3. Relay
It will help to test locally a lot.
Also there is small minor fix of docker-compose: links are replaced by names of services(instead of localhost).
> Launch moira locally

- metric_source/local/local.go
- vendor/vendor.json
Add applyByNode function, with initializing rewrite package.
Update carbon-api with one fix: https://github.com/go-graphite/carbonapi/commit/5a4fa2112923dd4c5d1a07164809a9da40dc0524
> Carbon api fixes

- api/controller/tag.go
- api/controller/tag_test.go
> fix deleting tags that are used in existing subscriptions

- .travis.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.filter
- Dockerfile.notifier
- Makefile
Go version bumped to 1.13.1 to fix problems occured during migration to
go modules.
> build: Bump go version

- Makefile
Tags for freature brances now contain commit hash and date.
> build: Change naming for feature docker images

- cmd/cli/main.go
- cmd/cli/user.go
> Add subscription transfer and contact deletion to CLI

- local/api.yml
- notifier/registrator.go
- senders/msteams/datatypes.go
- senders/msteams/msteams.go
- senders/msteams/msteams_test.go
Adds support for Microsoft Teams, via inbound channel WebHooks
* Add a delivery channel using the MSTeams Incoming Webhook 
* Assign the delivery channel to a Subscription (graphs are not yet supported)
Wait for the alerts to roll in the channel
> Msteams support

- go.mod
- go.sum
- index/bleve/trigger_index.go
Close #342
I'm testing here:
https://git.skbkontur.ru/moira-alert/staging/blob/master/charts/moira/values_main.yaml#L41
> Fix memory leak in Scorch-type index in Bleve 

- cmd/cli/user.go
Sometimes moira can send nil instead of subscription
> Check nil poiner

- senders/twilio/twilio.go
- senders/twilio/voice.go
- senders/twilio/voice_test.go
Use TwiML generator supported by TwilioLabs [link](https://www.twilio.com/labs/twimlets/echo). In this case instead of using `voiceurl` Echo url will be provided to Twilio as callback.
Managed by `twimlets_echo` parameter in Twilio Voice sender section
> Add twimlets support for Twilio sender

- cmd/telemetry.go
- docker-compose.yml
- go.mod
- go.sum
- local/prometheus.yml
- metrics/composite.go
- metrics/dummy.go
- metrics/graphite.go
- metrics/prometheus.go
> Add Prometheus endpoint for internal metrics

- filter/metrics_parser.go
- filter/metrics_parser_test.go
This fixes #489 (incorrect parsing of multiple equal signs in label).
> WIP: fix incorrect parsing of multiple equal signs in label

- filter/cache_storage.go
- helpers.go
- helpers_test.go
- notifier/plotting.go
- notifier/plotting_test.go
Fixed the missing point on the right side of plots.
Fix the missing right dot in non-realtime triggers due to rounding in redis.
Say we have two metric values for some non-realtime trigger.
|value|          ts          |        score       |    tsTime        |  scoreTime    |
|------|----------------|----------------|---------------|----------------|
|11    |   1582287284  | 1582287300  | 12:14:44 PM  |   12:15:00 PM|
|15    |   1582287344  | 1582287360  | 12:15:44 PM  |   12:16:00 PM|
Metric value 11 is the event that we want on a plot. 15 is a value that should get trimmed cause the trigger is not realtime. When notifier tries to fetch data, it specifies the right boundary as event's time plus one minute, so 12:15:45 PM (1582287345). Since fetch ranges values by score, we only get value …
> fix(notifier): Move plot boundaries

- filter/pattern_index.go
Tests show that with patterns from prod environment, 97% of calls to findPart produce at most 5 matches, so there is no need for creating a slice that big.
Changing capacity from 65 to 5 yields about 10% increase in performance of metric processor (7155 ns/op _vs_ 6279 ns/op)
> pefr(filter): Reduce nodes slice capacity

- .travis.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
- go.mod
- metric_source/remote/remote_test.go
> build: Upgrade to Go 1.14

- docker-compose.yml
Add Redis port exposure and auto-restart for all containers
> Improve docker-compose

- cmd/config.go
- database/redis/config.go
- database/redis/database.go
- database/redis/database_dialer.go
- database/redis/database_dialer_test.go
- database/redis/database_test.go
- database/redis/trigger.go
- filter/patterns_storage.go
- filter/patterns_storage_test.go
- interfaces.go
- mock/moira-alert/database.go
- perfomance_tests/filter/filter_test.go
Implemented reading patterns from slave replicas in an attempt to balance some load. Replicas may contain stale data, but it does not seem like a problem in case of updating the pattern index. 
Did not implement things like replica staleness checking or random replicas iteration. Should consider adding those sometime.
> Slave replicas read

- api/dto/triggers.go
- api/dto/triggers_test.go
- checker/check_test.go
- checker/config.go
- checker/fetch.go
- cmd/api/config.go
- cmd/checker/config.go
- cmd/cli/config.go
- cmd/config.go
- cmd/filter/config.go
- cmd/notifier/config.go
- database/redis/config.go
- database/redis/database.go
- database/redis/metric.go
- helpers.go
- interfaces.go
- local/api.yml
- local/checker.yml
- local/cli.yml
- local/filter.yml
- local/notifier.yml
- metric_source/local/local.go
- metric_source/local/local_test.go
- metric_source/remote/config.go
- metric_source/remote/remote.go
- metric_source/source.go
- mock/metric_source/source.go
- mock/moira-alert/database.go
Some users specify a very large number in TTL field of a trigger with intent to disable TTL functionality. This is a wrong approach: instead, users should set a different state to replace NODATA (e.g. NODATA → OK).
We should not let users set trigger TTL to more than:
1. `MetricsTTLSeconds` from checker config for local triggers.
2. Some sensible predefined constant that prevents OOM for remote triggers. For example, 1 week.
**Don't forget to merge moira-alert/helmcharts#7**
Idea of this PR changed dramatically after additional research. Here is the original PR summary for historical purposes:
`lastCheck.Timestamp` denotes a most recent point in time when a trigger was checked. While checking trigger, we are interested only in metric points after `lastCheck.Timestamp`, because all …
> Add cap on metric fetching to prevent checker OOM

- metrics/interfaces.go
- metrics/notifier.go
- notifier/events/event.go
Additional metrics to help analyzing spikes of delivered notifications.
Metric names: `...events.bystate.OK_to_NODATA`, etc.
Frankly, I don't understand why we have meters instead of counters here. I added these metrics as meters to maintain uniformity.
> feat(notifier): Add metrics for every possible state transition

- cmd/notifier/config.go
- database/redis/notification.go
- database/redis/notification_test.go
- integration_tests/notifier/notifier_test.go
- interfaces.go
- mock/moira-alert/database.go
- mock/notifier/notifier.go
- notifier/config.go
- notifier/notifications/notifications.go
- notifier/notifications/notifications_test.go
- notifier/notifier.go
Add params ReadBatchSize to notifier/config.go
Add 'limit' to FetchNotifications. Notification drops using "optimistic" transactions. See comment in fetchNotificationsWithLimitDo for more details.
Closes/Relates #501
> add limit to FetchNotifications function for read notifications from db

- api/dto/triggers.go
- api/dto/triggers_test.go
In api on save trigger is checked for validity. On alone metrics
validation regexp contain group that contains target number. This group
had incorrect index 0 in FindStringSubmatch that refers to whole match.
Instead of index 0 index 1 should be used.
Relates #428
> fix(api): Change regexp submatch index

- checker/check.go
- checker/errors.go
- checker/fetch.go
- checker/fetch_test.go
- checker/metrics/conversion/conversion.go
- checker/metrics/conversion/conversion_test.go
When checker pulls metrics after each fetch for target result of fetch
is checked for emptiness. This validation did not use last check result
that caused false errors when fetch result for target does not have
metrics
Relates #428
> fix(checker): Rewrite validation for empty targets

- checker/check.go
- checker/check_test.go
In checker the most hot place is a calls for getMetricDataState function. This PR tries to improve performance of this calls.
Relates #428
> perf(checker): Improve performance of check

- checker/errors.go
- checker/errors_test.go
ErrUnexpectedAloneMetric is an error that returned from check when
targets with alone metrics set by user do not match actual targets with
alone metrics. The message of this error is not very clear for users.
Now in error description we place a hint which targets should be marked
as a targets with alone metrics and which should not.
Relates #428
> feat(checker): Improve alone metrics error message

- checker/metrics/conversion/conversion.go
- checker/metrics/conversion/conversion_test.go
If all targets are marked as targets with alone metrics there is a
inconvenient which metric name should be used in check result. This
commit change default metric name from first alphabetical metric name to
metric name from T1.
Relates #428
> feat(checker): Change default metric name to T1

- api/dto/triggers.go
- api/dto/triggers_test.go
Temporary workaround that will deny to create triggers with * pattern in
targets.
SHOULD BE REMOVED AFTER #550 WILL BE RESOLVED
> fix(api): Deny usage of asterisk pattern

- cmd/telemetry.go
- filter/connection/handler.go
Add sending value to channel which is needed to close coroutines after TCP connection is closed.
Closes/Relates #560
> Fix goroutines leak in filter

- filter/connection/handler.go
Fixed multiple connections closing in Moira Filter when closing one of the tcp connection.
A go-routine leak was fixed in PR-562, but it caused closing multiple connections when any of them were close. I guess that this is because a channel named handler.terminate is common to all goroutines, spawned in any instance of the handle function. When any data send to this channel, several goroutines receive them and closing their connection. 
This PR suggests using an extra computation using the channel, named closeConnection to handle goroutine completion instead simple send any data into handler.terminate. This channel is local to each call to the handle function and the goroutine it spawns. Thus, when one connection will be closed, the goroutine, associated with the specific call to the …
> fix(filter): Fixed multiple connections closing in Moira-Filter caused by PR-562.

- api/handler/trigger_render.go
The `/trigger/{triggerID}/render` route is used to render the graph for a trigger. If no trigger with the matching triggerID is found, the API returns a 500 internal server error.
This commit changes it to return a 400 error instead with the corresponding message.
I think a 404 error is better for when a resource is not found, but I've used 400 so that it is consistent with other places where the trigger is nil (e.g deleting a trigger metric).
> fix(api): return 'not found' when rendering non-existing trigger chart

- api/handler/tiggers_test.go
- api/handler/triggers.go
Added search text converting to lowercase.
Closes/Relates #512
> Fix full-text search if the text is in uppercase

- senders/telegram/send.go
- senders/telegram/send_test.go
Added the ability to set the identifier of private channels for notifications. It starts with `%`.
Closes #563
> feat(telegram): Added private channels support

- senders/slack/slack.go
Hello, 
My team has a single channel for alerts across all our applications. For each application we added a separate Slack user-group (`@gitlab_duty`/`@teamcity_duty` for example) that contains one or several engineers on duty and we would like to mention these groups in the alert message. 
Moira uses Slack API `chat.postMessage` for sending alert messages and that requires us to specify that user group by using the rather complicated syntax `<!Subteam^SAZ94GDB8>` (see https://api.slack.com/reference/surfaces/formatting#mentioning-groups). We can't get user-group ID from the Slack Desktop App and we have to use Slack API in order to do that.
There is another way: we can specify additional property `Parse` with value `full` in PostMessageParameters which change how Slack treats the …
> Add support of Slack user-group mentioning in the alert message

- Makefile
- senders/slack/slack.go
Older version stopped working on Travis CI for some reason.
> build: Bump golangci-lint version

- checker/check.go
- checker/check_test.go
- checker/metrics/conversion/conversion.go
- checker/metrics/conversion/conversion_test.go
- checker/metrics/conversion/trigger_metrics.go
- checker/metrics/conversion/trigger_metrics_test.go
Targets in trigger can be marked as a "Single" what is mean that in
this target will be only one metric. If target have one metric and it is
not marked as "Single" check of this trigger will set trigger to
exception state as it was expected to have more than one metric in this
target.
This commit changes behavior of checker to allow targets not marked as
alone to have only one metric.
Relates #428
> feat(checker): Allow targets be single if it not declared

- api/controller/trigger.go
- api/controller/trigger_test.go
- datatypes.go
In last check some targets have a records in MetricsToTargetRelation
dictionary. This records did not cleaned during trigger update that led
checker to use metric names from this dictionary to populate the set of
metrics to check.
Closes #593
> Clean last check on trigger update

- api/handler/trigger.go
In trigger update handler were used check for populate description. This
check is not necessary in trigger update and causes panic because it
tries to check "populated" query param that is not allowed for this
route.
Relates #182
> fix(api): Remove populate check in trigger update

- api/controller/triggers.go
- api/controller/triggers_test.go
- api/dto/triggers.go
- api/handler/triggers.go
- database/redis/triggers_search_results.go
- database/redis/triggers_search_results_test.go
- interfaces.go
- mock/moira-alert/database.go
Add pager deletion endpoint to API
> feat(api): Add pager deletion

- senders/webhook/request.go
- senders/webhook/request_test.go
Bug with webhook: url has encoded slashes if contact value looks like `http://ya.ru/`.
> fix http schema escaping when build url in webhook sender

- database/goredis/config.go
- database/goredis/database.go
Раньше были два отдельный коннекшена: на мастер и на слейв, всё по дефолту читалось и писалось на/с коннекшн мастера, потом некоторые сущности принудительно сделали возможными для чтения со слейва, чтобы разгрузить мастер, но не все!
Горедис делает возможным ВСЁ чтение делать со слейвов, и потребность в таком принудительном разделении отпала.
> Move to go-redis (database sentinel) 

- database/redis/trigger.go
- database/redis/trigger_test.go
There was a message like this in console:
```
checker ERR NODATA check failed: failed to get triggers-list: CROSSSLOT Keys in request don't hash to the same slot module=checker
```
Error was in `GetLocalTriggerIDs` (`SDiff`)
> Fixed trigger list manipulations on redis cluster

- database/redis/tag.go
- database/redis/tag_test.go
There was an error in `getTriggersIdsByTags` (`SInter`) because the keys of tags were in different slots.
> Fixed trigger tags manipulation on redis cluster

- filter/metrics_parser.go
- filter/patterns_storage.go
- filter/patterns_storage_test.go
Tag metrics are checked only on tag patterns. Plain metrics are checked only on plain patterns.
> Improved speed of metrics matching in filter

- cmd/cli/cluster.go
- cmd/cli/cluster_test.go
- cmd/cli/main.go
- database/redis/bot_test.go
- database/redis/contact_test.go
- database/redis/database.go
- database/redis/database_test.go
- database/redis/last_check_test.go
- database/redis/locks_test.go
- database/redis/metric_test.go
- database/redis/notification_event_test.go
- database/redis/notification_test.go
- database/redis/selfstate_test.go
- database/redis/subscription_test.go
- database/redis/tag_test.go
- database/redis/teams_test.go
- database/redis/throttling_test.go
- database/redis/trigger_test.go
- database/redis/triggers_lock_test.go
- database/redis/triggers_search_results_test.go
- database/redis/triggers_to_check_test.go
- database/redis/triggers_to_reindex_test.go
- database/redis/unused_triggers_test.go
There were 5 renames of keys (2 [here](https://github.com/moira-alert/moira/pull/679),  1 [here](https://github.com/moira-alert/moira/pull/684), 2 [here](https://github.com/moira-alert/moira/pull/683)) to migrate to Redis Cluster
In this PR added a command that renames existing keys in the database.
1. compile cli
```bash
$ go build -o build/cli github.com/moira-alert/moira/cmd/cli
```
2. run command forwards
```bash
$ ./build/cli -config local/cli.yml -move-to-cluster-forwards
```
```bash
2021-12-01 09:14:23.604 cli INF Moving to cluster forwards module=cli
2021-12-01 09:14:23.606 cli INF renameAnyTagsSubscriptionsKeyForwards done module=cli
2021-12-01 09:14:23.606 cli INF renameTriggersListKeyForwards done module=cli
2021-12-01 09:14:23.606 cli INF renameRemoteTriggersListKeyForwards …
```
> Added command to transform keys to work on Redis Cluster

- cmd/api/config.go
- cmd/checker/config.go
- cmd/cli/config.go
- cmd/config.go
- cmd/filter/config.go
- cmd/notifier/config.go
- database/redis/config.go
- database/redis/database.go
Go-redis lib provides a way to configure timeouts for redis connections. Corresponsing settings have been placed in Moira config file with following defaults:
- Dial timeout: 0.5 s (current master default)
- Read timeout: 3 sec (go-redis default), infinity on current master ([default if not specified in redigo](https://github.com/gomodule/redigo/issues/372))
- Write timeout: 3 sec (go-redis default), infinity on current master (default if not specified in redigo)
> Made redis timeout settings editable

- go.mod
- go.sum
This update fixes work of [bleve](https://github.com/blevesearch/bleve) on arm64
> Updated module github.com/golang/snappy

- database/database.go
- database/redis/locks.go
- database/redis/locks_test.go
- worker/worker_test.go
Previously, it was very uninformative: it was not clear what happened. It now contains more detailed information.
New error real example:
> lock was not acquired: 1 error occurred:\n\t* NOPERM this user has no permissions to run the 'eval' command or its subcommand\n\n
> Improved ErrLockNotAcquired

- .run/go test moira.run.xml
The number of tests that run simultaneously in parallel is the current value of `GOMAXPROCS` (normally the number of CPUs available) by default.
It can cause some tests to fail (for reason reading/writing values from one database).
To avoid such a situation, you need to specify a parameter `-p n`  (the number of programs, such as build commands or test binaries, that can be run in parallel).
So that everyone does not have to customize the launch of tests, added [GoLand shared test run configuration](https://www.jetbrains.com/help/go/run-debug-configuration.html#share-configurations).
> Added shared test configuration for GoLand

- docker-compose.yml
Better to enclose in double-quotes
https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
> Fixed redis port exposing

- notifier/notifier.go
This PR simply decreases level of logging for broken contact errors (`SenderBrokenContactError`) in order to clean up a bit error-level logs for notifier module
> Decreased level of logging for broken contact errors to 'warning'

- cmd/api/main.go
- cmd/checker/main.go
- cmd/cli/main.go
- cmd/notifier/main.go
Automaxprocs automatically sets GOMAXPROCS to match Linux container CPU quota.
Relates #712
> Added automaxprocs package to api, checker, cli, notifier

- database/redis/database.go
- database/redis/metric.go
In the case of Redis Cluster, which node the channel hit, it becomes very loaded. To avoid this situation, the channel was sharded. Also made some refactoring to keep logic in the `master` branch.
> Sharded channels

- plotting/curve.go
- plotting/curve_test.go
- plotting/limits.go
- plotting/limits_test.go
- plotting/plot_test.go
There was a gap in filtering of metric values and Ininity values were passed to further processing, particularly to plotting. That causes errors ike:
```
Can't build notification package plot for {trigger.id}: infinite y-range delta
```
Now filtering is added in.
> Fixed plotting error in notifier

- cmd/cli/cluster.go
- cmd/cli/cluster_test.go
- cmd/cli/from_2.6_to_2.7.go
- cmd/cli/main.go
To upgrade to version 2.7 with Redis Cluster support:
`% ./build/cli --config local/cli.yml --update --from-version=2.6`
To downgrade to previous version 2.6 without Redis Cluster support:
`% ./build/cli --config local/cli.yml --downgrade --to-version=2.6 `
> Reworked command to add/remove Redis Cluster support

- senders/telegram/send.go
- senders/telegram/send_test.go
Broken contact errors are basically kind of rare user scenarious treated separately. Particularly they aren't resent and they are just warnings in logs. This PR extends that list with couple of telegram-specific scenarious:
- Bot rights are restricted (`ErrNoRightsToSendPhoto`, `ErrNoRightsToSend`)
- Chat not found (`ErrChatNotFound`)
> Extended list of broken contact errors

- .github/workflows/lint.yml
- cmd/cli/config.go
- cmd/cli/main.go
- cmd/cli/metrics.go
- cmd/cli/metrics_test.go
- database/redis/metric.go
- database/redis/metric_test.go
- interfaces.go
- local/cli.yml
- mock/moira-alert/database.go
To run command to clean up outdated metrics by default, older than 7 days:
```bash
$ ./moira-cli --config local/cli.yml -cleanup-outdated-metrics
```
You can change this option in `local/cli.yml`:
```yaml
cleanup_metrics_duration: "-168h"
```
> Added command to clean up outdated metrics

- api/controller/trigger.go
- api/controller/trigger_metrics.go
- api/controller/trigger_test.go
- cmd/cli/metrics_test.go
- database/redis/last_check.go
- database/redis/triggers_lock.go
- database/redis/triggers_lock_test.go
- interfaces.go
- mock/moira-alert/database.go
This PR fixes an issue with infinite loop on setting trigger to maintenance. The solution is the using of trigger locks, which are already part of other trigger related functions like `saveTrigger` and `deleteTriggerMetrics`.
> fix(api): Fixed setting trigger check maintenance

- go.mod
- go.sum
Updated github.com/go-graphite/carbonapi to v0.15.3, because Moira have panic while do checks
> Updated github.com/go-graphite/carbonapi to v0.15.3

- go.mod
- go.sum
- metric_source/local/local_test.go
revert this [pull request](https://github.com/moira-alert/moira/pull/739)
> Reverted update github.com/go-graphite/carbonapi to v0.15.4

- cmd/filter/config.go
- cmd/filter/main.go
- database/redis/metric_test.go
- filter/matched_metrics/metrics.go
- filter/metrics_parser.go
- filter/metrics_parser_test.go
- filter/patterns/matcher.go
- filter/patterns_storage.go
- filter/patterns_storage_test.go
- log_fields.go
- metrics/prometheus.go
- perfomance_tests/filter/performance_test_utils.go
- support/trigger.go
If metric_timestamp + drop_metrics_ttl before now, we don`t save this metric. In other way we will use this metric for further work.
> Added into filter drop_metrics_ttl attribute

- filter/patterns_storage.go
Decreased log-level for too old metric, because it make much noise in logs now.
> Decreased log-level for too old metric

- cmd/cli/main.go
- cmd/cli/metrics.go
- cmd/cli/metrics_test.go
- database/redis/metric.go
- database/redis/metric_test.go
- generate_mocks.cmd
- interfaces.go
- mock/moira-alert/database.go
_Abandoned/outdated keys_ are keys for metrics for which corresponding metric data key doesn't exist, so these abandoned/outdated keys are trash in database and it should be deleted for database consistency.
Added cleanup for abandoned/outdated pattern metrics and metrics retentions, move cleanup of abandoned/outdated keys to one CLI command.
> Improved metrics cleanup cli

- .github/workflows/lint.yml
We make image for running linters as "fixed" version. We don't use latest verstion.
> fix(ci): Fix ubuntu image for linters

- cmd/cli/main.go
There is need to run cleanups separately to detect errors. Separated cleanups.
> Separated cleanups

- database/redis/metric.go
- database/redis/metric_test.go
Pattern from moira-pattern-list key has no sense if pattern-metrics key doesn't exist, so that patterns are trash in database. Now patterns would be removed on cleanup.
**Don't do this**, see [comment](https://github.com/moira-alert/moira/pull/785#issuecomment-1221920426)
> Added cleanup for abandoned patterns

- filter/patterns_storage.go
There is case when users have problems, so we need to make sure that metrics is not matched.
> Added logging for not matched metrics

- checker/worker/remote.go
- metrics/checker.go
This PR adds a new internal Moira metric `moira.checker.remote.unavailable` which is supposed to show the number of graphite API call failures.
> feat: Added specific metric for graphite unavailability check result

- cmd/cli/main.go
- cmd/cli/triggers.go
- database/redis/tag_test.go
- database/redis/trigger.go
- database/redis/trigger_test.go
- interfaces.go
- mock/moira-alert/database.go
There is a problem - one of teams of Moira users have unused triggers. So it is a trash in database. Added command to remove triggers which have ID starting with prefix.
> Added new cmd to remove triggers

- api/controller/contact_test.go
- api/error_response.go
- api/handler/handler.go
- api/middleware/logger.go
- metric_source/remote/request.go
- senders/msteams/msteams_test.go
- senders/victorops/api/alert.go
- senders/webhook/webhook.go
Using http package consts instead bare numbers for http codes
> net/http library's consts for representing http codes

- api/controller/triggers.go
- api/controller/triggers_test.go
User could crate triggers with custom name that contains invalid characters. Added validation in trigger controller.
Add tests for cases with correct and incorrect trigger ID.
> Add trigger ID validation

- api/controller/triggers.go
- api/controller/triggers_test.go
Original validation was too strict. It prohibited some trigger ids that were actually in use
- It turned out to be too difficult to create exhaustive character blacklist.
- Some symbols that are allowed by rfc break our webpage (e.g. `&` or `$'` combintation)
So I've decided to update the whitelist to include all the cases that we know of. I've downloaded and validated all triggers in producation database, to make shure no currently used trigger will be affected
> fix(api): Widen range of valid ids

- api/dto/target.go
- api/dto/target_test.go
There was a bug: user could create trigger with target with space in metric name like `a b`. Now validation doesn't allow it.
> Fix target validation

- cmd/cli/main.go
- cmd/cli/metrics.go
- database/redis/tag.go
- database/redis/tag_test.go
- interfaces.go
- mock/moira-alert/database.go
Abandoned tags are tags without triggers and subscriptions, so it is a trash in database and affects users in Web UI, these tags should be removed. Now tags would be removed on cleanup.
> Added cleanup abandoned tags

- api/dto/target.go
- api/dto/triggers.go
- api/handler/trigger.go
- api/handler/trigger_test.go
- api/handler/triggers.go
- api/handler/triggers_test.go
There is a problem that client sides should call /trigger/check/ API for validation, but obviously it is not necessary. As a result we have invalid triggers in DB. The plan consists of next steps:
1. Test current createTrigger and updateTrigger API.
2. Add new version of createTrigger and updateTrigger API with validation and test it. New version should not affect prev version, It is important for backward compatibility, because Moira is follows API first approach.
Then in another PRs update client sides to use new version of APIs.
> Validate trigger target on create/update

- database/redis/notification_event_test.go
- go.mod
- go.sum
- metrics/prometheus.go
- senders/mattermost/sender_manual_test.go
>  Update prometheus version and change deprecated methods

- templating/templating.go
Make strings.Split function available in description templates
> Make strings.Split function available in description templates

- filter/series_by_tag.go
- filter/series_by_tag_pattern_index_test.go
This PR fix `series by tags` parser. 
1. Fix regular expression for correct work with regular expressions in tags. Example: `seriesByTag("respCode=~^(4|5)\d{2}")`
2. Now transform function applied to every tag spec. Not for whole value in `seriesByTag()`.
3. If spec was tranformed change `operator` from `equal` to `match`.
Closes #823
> fix(filter): fix regex in series by tag parser

- .github/workflows/test.yml
- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
- go.mod
- Generics. We can use [constraints](https://pkg.go.dev/golang.org/x/exp/constraints)
- Type `any` is alias for `interface{}`
- Fuzzing. Is a new kind of tests, which runs tests with different input to find errors in boundary conditions
TODO:
- Use `any`
- Use Generics
> Updated golang to 1.18

- checker/check.go
- checker/check_test.go
- database/redis/last_check.go
- senders/pagerduty/send.go
fix transition to ERROR state when duplicating metrics
Replaced the ERROR condition with EXCEPTION for duplicate names in `checker/check.go`, fixed the corresponding tests
Also fixed 2 linter errors in `database/redis` and `senders/pagerduty`
> fix(checker): fix transition to ERROR state when duplicating metrics

- helpers.go
- helpers_test.go
- senders/telegram/handle_message.go
- senders/telegram/init.go
- senders/telegram/send.go
I decided it wasn't so terrible to rely on telegram's api, so I didn't remove the token link entirely, just replaced the token with `[DATA DELETED]`, knowing that the token is enclosed between `/bot` and the following `/` based on telegram's api documentation:
> All requests to the Telegram Bot API must be made via HTTPS in the following form: https://api.telegram.org/bot<token\>/METHOD
For example:
https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe
> fix(senders): remove telegram token from error message

- api/handler/trigger.go
It seems like it was just done for one-time testing, but then just forgotten about
> fix(api): remove panic in get trigger function

- api/handler/notification.go
- api/handler/notification_test.go
- api/handler/trigger_metric_test.go
- api/handler/trigger_metrics.go
- api/handler/trigger_render.go
- api/handler/trigger_render_test.go
- api/middleware/context.go
- api/middleware/context_test.go
- docker-compose.yml
- go.sum
This is done in order to get rid of error silence in case query string could not be unparsed
> fix(api): add the parse query function instead of query

- .github/workflows/swagger-delete.yml
Made the same call conditions as job with publishing
> fix: hotfix swagger delete job

- cmd/notifier/config.go
- cmd/notifier/main.go
- metrics/heartbeat.go
- notifier/notifications/notifications.go
- notifier/selfstate/check.go
- notifier/selfstate/config.go
- notifier/selfstate/heartbeat/heartbeat.go
- notifier/selfstate/heartbeat/notifier.go
- notifier/selfstate/heartbeat/notifier_test.go
- notifier/selfstate/selfstate.go
- notifier/selfstate/selfstate_test.go
> add metric in notifier-selfcheck

- api/controller/trigger.go
- api/controller/trigger_test.go
- checker/check.go
- checker/check_test.go
- cmd/cli/cluster.go
- datatypes.go
- local/checker.yml
Added a flag `DeletedButKept` which means whether the metric will be shown to the user if it should be deleted by TTL trigger but is on Maintenance, there are several possible events:
1) The TTL of the trigger that has TTLState = Del has expired:
- if the metric is not on Maintenance or its Maintenance time has expired, it is immediately deleted
- if the metric is on Maintenance and `DeletedButKept` is false, then we set `DeletedButKept` = true, the metric remains in the database, but will not be shown to the user
2) The TTL of the trigger has not expired:
- if the metric is on Maintenance, its `DeletedButKept` is true and a new metric arrives, then `DeletedButKept` becomes false and the metric starts to be shown to the user
The state of the metric is updated
Close/relates: #530
> fix(checker,api): fix switch to maintenance at set del

- docker-compose.yml
Last time [openmetric/carbon-c-relay](https://registry.hub.docker.com/r/openmetric/carbon-c-relay/tags) was build almost 4 years ago. Obviously, it doesn't support arm, so it runs under emulation on m1/m2 macbooks.
> fix: switch to a maintained version of carbon-c-relay

- .github/workflows/docker-nightly.yml
fix(build): add tag 'latest' to nightly images
Currently, "nightly" images are generated without the "latest" tag. Fix corrects this behavior so that you can always pull the latest image when building the service.
> fix(build): add tag 'latest' to nightly images

- checker/worker/handler.go
Partially reverts #933 due to multiple errors that appeared in logs after fixing panic handling in checker
> Revert panic logging in checker

- cmd/api/main.go
Currently, RemoteAllowed controls if triggers of both "remote" types (remote graphite and prometheus) could be created, but it is calculated only based on remote graphite config.
In our case we only use prometheus triggers, so it is a little odd to fill in remote graphite config section (to set `Enabled: true`) to be able to create prometheus triggers.
> fix: RemoteAllowed calculation

- cmd/notifier/main.go
- integration_tests/notifier/notifier_test.go
- metrics/notifier.go
- notifier/notifications/notifications.go
- notifier/notifications/notifications_test.go
A metric that determines the fetching time of notifications can help in determining `transaction_timeout`
> feature(metrics): add fetch notifications metric

- filter/metrics_parser_test.go
- go.mod
- go.sum
- metric_source/local/eval.go
- metric_source/local/local_test.go
This reverts commit f534208d75070616b3a114643cd829dca5372df8.
> Revert "fix(cheker,api,notifier): update carbonapi to v0.16.2-0 (#947)"

- cmd/api/main.go
- cmd/checker/main.go
- cmd/cli/main.go
- cmd/config.go
- cmd/filter/main.go
- cmd/notifier/config.go
- cmd/notifier/main.go
- database/redis/config.go
- database/redis/contact_notification_history_test.go
- database/redis/database.go
- database/redis/last_check.go
- database/redis/last_check_test.go
- database/redis/metric.go
- database/redis/notification.go
- database/redis/notification_test.go
- database/redis/reply/check.go
- database/redis/reply/notification.go
- database/redis/reply/notification_test.go
- datatypes.go
- datatypes_test.go
- go.mod
- helpers.go
- helpers_test.go
- local/notifier.yml
- notifier/events/event_test.go
- notifier/notifier.go
- notifier/scheduler.go
- notifier/scheduler_test.go
This PR solves the problem of unwanted notifications being sent on triggers or metrics to Maintenance or removed triggers
Add notification config, in detail:
- `delayed_time` - if the difference between notification sending time (timestamp) and creation time (created_at) is greater than this time, then the notification is considered delayed, otherwise it is considered not delayed
- `transaction_timeout` - timeout time between transactions in fetchNotifications
- `transaction_max_retries` - maximum number of transactions in fetchNotifications
- `transaction_heuristic_limit` - limit, if exceeded, all notifications will be fetched from the database
Add additional functions:
- `getTriggersLastCheck` function, with which I will be able to get `checkData` for each trigger passed in the …
> feat(notifier): fix sending notifications on muted and deleted triggers and metrics

- checker/worker/worker.go
- cmd/checker/config.go
- database/redis/trigger.go
Fixed the default `MaxParallelChecks` in the checker config and added correct filling `MaxParallelPrometheusChecks`
> fix(checker): fix checker settings

- cmd/cli/main.go
Added a new command to delete given subscriptions separated by semicolons
Example: `cli --remove-subscriptions 'id1; id2; id3'`
> feat(cli): add remove subscriptions command

- api/controller/trigger_metrics.go
- api/dto/triggers.go
- checker/check.go
- checker/metrics/conversion/alone_metrics.go
- checker/metrics/conversion/alone_metrics_test.go
- checker/metrics/conversion/trigger_metrics.go
- metric_source/metric_data.go
Fixes a bug occurring when toggling the checkbox on alone metrics due to the false value passed from the frontend under the corresponding target
> fix(checker): fix nodata when toggling alone metrics checkbox

- api/dto/target.go
- api/dto/target_test.go
This PR is intended to prevent Moira from saving too many metrics locally when someone creates/edits a trigger with a target that can match a lot of them.
With these changes seriesByTag must have at least one argument with equality operator and no wildcards.
- `movingAverage(groupByTags(seriesByTag('project=my-test-project'), 'max'), '10min')`
- `aliasByTags(seriesByTag('name=~*', 'tag1=val1', 'tag2=val2', 'tag3=val3*'),'tag')`
- `seriesByTag('name=ab.bc.*.cd.*.ef')`
- `aliasByTags(seriesByTag('name=~*'),'tag')`
- `aliasByTags(seriesByTag('name=~*', 'tag1~=*val1*', 'tag2=*val2*'),'tag')`
> fix(api): make triggers with seriesByTag function require at least one argument with a strict equality

- api/handler/handler_test.go
- api/handler/tag.go
Allow usage of `/api/tag/stats` for non-admins
> feat(api): Allow tag stats for non api triggers

- cmd/filter/config.go
- cmd/filter/main.go
- filter/matched_metrics/metrics.go
Add `BatchForcedSaveTimeout` to filter config. It regulates, how often metric batches are forced to be saved
> feat(filter): Move batch forced save timeout to config

- cmd/cli/config.go
- cmd/cli/main.go
- cmd/cli/metrics.go
- cmd/cli/metrics_test.go
- database/redis/metric.go
- database/redis/metric_test.go
- filter/metrics_parser.go
- filter/metrics_parser_test.go
- filter/patterns_storage.go
- interfaces.go
- local/cli.yml
- mock/moira-alert/database.go
Added ability to delete metrics via `--cleanup-future-metrics` command in cli with specifying `cleanup_future_metrics_duration` parameter in config, starting from which metrics written to the future will be deleted
Also added discarding metrics whose timestamp is greater than `now() + dropMetricsTTL` to avoid writing garbage to the database
And accelerated tests by 8 seconds by replacing `time.Sleep` with `metricsCache.Flush`.
> feat(filter,cli): add remove future metrics in cli and discarding metrics written into the future

- api/controller/contact.go
- api/controller/contact_test.go
- api/controller/subscription.go
- api/controller/subscription_test.go
- api/dto/subscription.go
- api/dto/subscription_test.go
- api/handler/contact.go
- api/handler/contact_test.go
- api/handler/subscription.go
- api/handler/team_contact.go
- api/handler/team_subscription.go
Now admins can create contacts and subscriptions for other users and teams
If some non-admin user `A` tries to create subscription for other user `B` it is created for `A` instead for backwards compatibility
> Add ability for admins to create contacts and subscriptions for other users and teams

- cmd/cli/main.go
Removed the `moira-pattern-metrics` key clearance from the `cleanup-metrics` cli key and added `cleanup-pattern-metrics` to the `cleanup-pattern-metrics` cli key
> fix(cli): add cleanup pattern metrics cli key

- Dockerfile.api
- Dockerfile.checker
- Dockerfile.cli
- Dockerfile.filter
- Dockerfile.notifier
Update go image in docker build layers to golang:1.21
> Update go in docker to 1.21

- api/controller/contact.go
- api/controller/contact_test.go
- api/dto/contact.go
- api/handler/contact_test.go
- datatypes.go
Add support for custom names in backend contacts
Closes #1018
> feat(api): add custom name to contacts

- api/controller/contact.go
- api/controller/contact_test.go
Now validation on contact types stops working with the admin turned off
> hotfix(api): forbidden create unresolved contact type

- database/redis/metric.go
- database/redis/metric_test.go
- local/checker.yml
Added fetching metrics to the redis pipeline
In addition, conducted benchmarks testing the performance of the solution on N number of unique metrics with 10 points each, the solution with pipeline greatly reduced the time to get values by metrics, but required more allocations
`old` - old solution without pipeline
`new` - new solution with pipeline
```
benchmark                                     old ns/op      new ns/op     delta
BenchmarkGetMetricValues/100-metrics-12       67507442       3536363       -94.76%
BenchmarkGetMetricValues/1000-metrics-12      512515118      26622719      -94.81%
BenchmarkGetMetricValues/5000-metrics-12      2600663168     94167600      -96.38%
BenchmarkGetMetricValues/10000-metrics-12     4881419523     179366564     -96.33%
benchmark …
```
> perf(checker): add fetching metrics values in pipe

- .github/workflows/test.yml
- Makefile
The speed of passing the tests increased by about 3 min
> fix: remove benchmarks from ci

- filter/metrics_parser.go
`restoreMetricStringByNameAndLabels` is called when parsing metrics, accordingly with a large volume of metrics the number of allocations and perfomance start to be greatly affected
```go
func BenchmarkWriteStringFmt(b *testing.B) {
var testStr string
for i := 0; i < b.N; i++ {
testStr = fmt.Sprintf(";%s=%s", abcde, abcdeabcde)
}
_ = testStr
}
func BenchmarkWriteStringPlus(b *testing.B) {
var testStr string
for i := 0; i < b.N; i++ {
testStr = ";" + abcde + "=" + abcdeabcde
}
_ = testStr
}
func BenchmarkWriteStringBuilder(b *testing.B) {
var testStr string
for i := 0; i < b.N; i++ {
builder := strings.Builder{}
builder.WriteString(";")
builder.WriteString(abcde)
builder.WriteString("=")
builder.WriteString(abcdeabcde)
testStr = builder.String()
}
_ = testStr
}
```
And the result:
``` …
```
> feat(filter): improve perfomance or restoreMetricStringByNameAndLabels

- local/checker.yml
Increased `stop_checking_interval` in the checker config so that users don't encounter the problem of quickly stopping checking local triggers
> chore: increase local stop checking interval

- api/dto/triggers.go
- api/dto/triggers_test.go
- api/handler/triggers_test.go
- datatypes.go
Lack of default values ​​may lead to incorrect behavior.
> refactor(api): add some default vals to TriggerModel

- api/dto/triggers.go
- api/dto/triggers_test.go
Before this PR `"alone_metrics"` with format like `{"t1 t2": true}` was treated as valid (valid form is: `{"t1": true, "t2": true}`). After this PR it will be considered invalid.
> refactor(api): validating of target name in alone metrics

- filter/series_by_tag.go
- filter/series_by_tag_pattern_index_test.go
It doesn't make sense to create a new regular expression for tags like `tag=~*`, `tag=~.*`, `tag!=~*` or `tag!=~.*`, because in such tags it is the fact of presence or absence of a tag that matters, not its value. This can reduce the total number of expensive `regexp.MatchString` operations in filters
> perf(filter): improved handling of non-strict asterisk tags

- cmd/cli/main.go
- cmd/config.go
- cmd/notifier/config.go
- cmd/notifier/main.go
- datatypes.go
- integration_tests/notifier/notifier_test.go
- local/notifier.yml
- logging/zerolog_adapter/logger.go
- mock/scheduler/scheduler.go
- notifier/config.go
- notifier/events/event.go
- notifier/events/event_test.go
- notifier/notifier.go
- notifier/notifier_test.go
- notifier/scheduler.go
- notifier/scheduler_test.go
This PR is a copy of #1046 by @AleksandrMatsko
> refactor(notifier): rescheduling delay

- senders/telegram/init.go
If someone used `<`, `>`, `&` in trigger title or in metrics then telegram can not parse message.
> hotfix(sender/telegram): escape-html-specials-in-tg-sender

- go.mod
- go.sum
Updating the go-chart version to fix a bug that caused notifier to have increased CPU consumption because the go-chart had an infinite loop
> chore: update go chart version

- api/controller/events.go
- api/controller/events_test.go
- api/handler/constants.go
- api/handler/event.go
- api/handler/trigger.go
- api/handler/trigger_test.go
- api/middleware/context.go
- api/middleware/context_test.go
- api/middleware/middleware.go
- database/redis/notification_event.go
- database/redis/notification_event_test.go
- interfaces.go
- mock/moira-alert/database.go
- mock/scheduler/scheduler.go
- state.go
Offered query parameters are:
- `from` - start of time range
- `to` - end of time range
- `metric` - regular expression which will be used on `NotificationEvent.Metric` field
- `states` - separated string of states, separator is `','`
> feat(api): query parameters to trigger events

- notifier/scheduler.go
- notifier/scheduler_test.go
The problem occurred when sending notifications in a subscription with a schedule of 11:30 PM - 06:00 PM in which the end was earlier than the beginning, i.e. it was supposed to go to the next day
In the test cases there was a similar example with the schedule from 02:00 AM - 00:00 AM earlier, but in this case everything happens **within one day**, which did not allow to detect the bug
In this PR I have fixed this incorrect behaviour by adding additional handling for the case where the end of the schedule is earlier than the beginning. Let's look at an example:
- We have a subscription with a schedule from 11:30 PM - 06:00 PM
- A metric came to us that generated an alert at 02:00 PM
- Before this PR we would only increment the 06:00 PM to the next day, not taking into account that the …
> fix(notifier): fixed sending of notifications with schedule between different days

- api/controller/contact_events_test.go
- api/controller/events.go
- api/controller/events_test.go
- api/handler/constants.go
- api/handler/contact_events.go
- api/handler/event.go
- api/handler/trigger.go
- api/handler/trigger_test.go
- api/middleware/context.go
- api/middleware/context_test.go
- api/middleware/middleware.go
- database/redis/notification_event.go
- database/redis/notification_event_test.go
- interfaces.go
- mock/moira-alert/database.go
- mock/scheduler/scheduler.go
- state.go
Offered query parameters are:
- `from` - start of time range (default value `-inf`)
- `to` - end of time range (default value `+inf`)
- `metric` - regular expression which will be used on `NotificationEvent.Metric` field (default value `.*`)
- `states` - separated string of states, separator is `','`, if empty means all states (empty by default)
> feat(api): query params to event history

- api/controller/contact.go
- api/controller/contact_test.go
- api/controller/subscription.go
- api/dto/contact.go
- api/dto/subscription.go
- api/handler/contact_test.go
- local/api.yml
Users now have the ability to move their contacts to a team and vice versa. Subscriptions can also be moved from a user to a team, but only if you are a member and vice versa
> feat(notifier): add ability to move contacts and subscriptions between users and teams

- .github/workflows/swagger-publish.yml
We have different versions for uploading and downloading artifacts in swagger-publish action.
This PR ups the versions of `node` and `upload-artifact`
> fix: up node version and upload artifact version in swagger publish

- senders/telegram/init.go
- senders/telegram/init_test.go
Package telebot used in tg sender has internal logging, and when error occurs it writes uri (**with token!**) to logs.
This PR fixes it.
> refactor: hide credentials in tg sender

- api/controller/contact.go
- api/controller/contact_test.go
- api/handler/contact.go
- api/handler/contact_test.go
- api/handler/handler.go
- api/handler/team_contact.go
- api/middleware/context.go
- api/middleware/middleware.go
- cmd/api/config.go
- cmd/api/config_test.go
- cmd/api/main.go
Previously contact template validation in web config was on the frontend, I moved it to the backend and added validation of the templates themselves
> feat(api): contact template validation

- api/handler/handler.go
- api/handler/team_contact_test.go
Add middleware `ContactsTemplateContext`  to `teams` router
> hotfix(api): adding contacts to team

- api/controller/triggers.go
- api/controller/triggers_test.go
Added a trigger id to api response on creating trigger (PUT /api/trigger/)
None
None
> feat(api): print trigger id when it already exists

- filter/prefix_tree.go
- filter/prefix_tree_test.go
- filter/series_by_tag_pattern_index.go
Профилировки показали, что заполнение и чтение мапы в методе MatchWithValue префиксного дерева потребляет порядка 18% времени CPU в фильтрах. Заменил заполнение мапы на передачу колбека
> perf(filter): Optimize maps read/writes in hot path

- filter/series_by_tag_pattern_index.go
Обратили внимание, что итерация по мапе занимает порядка 8% производительности фильтра, решили заменить её на слайс
> perf(filter): replace map with slice in hot path

- api/dto/triggers.go
- api/dto/triggers_test.go
- api/handler/triggers_test.go
- datatypes.go
Before this PR `Trigger` with not all days in the schedule could be created.
Now the following rules will be applied:
- if some days are missed they will be marked `Enabled = false`;
- if day name not in `[Mon, Tue, Wed, Thu, Fri, Sat, Sun]` the error will be returned;
- if days are unordered they will be ordered from `Mon` to `Sun`;
- if there is no days with `Enabled = true` the error will be returned;
> fix: trigger schedule fill

- api/config.go
- cmd/api/config.go
- cmd/api/config_test.go
Added into config ability to set celebration mode.
> feat(api): add celebration mode

- api/dto/triggers.go
- api/dto/triggers_test.go
Before this PR you could create trigger with `seriesByTag` function, that have invalid regular expressions in tag values.
Now validation is added.
> feat: validate trigger patterns

- checker/check.go
- checker/check_test.go
- metric_source/local/errors.go
- metric_source/local/eval.go
In #1085 retries to Graphite remote metrics source were added. So new error `ErrRemoteUnavailable` was added. 
This PR refactors checker logic to proper handle `ErrRemoteUnavailable` and `ErrRemoteTriggerResponse`. Also add tests for handling fetch errors
> fix: checker handle source unavailable

- api/controller/contact.go
- api/controller/contact_test.go
- api/controller/team.go
- api/controller/team_test.go
- api/dto/contact.go
- api/dto/team.go
- api/handler/contact_test.go
Replace moira.ContactData with dto.TeamContact, deprecate team field
> fix: Unify contact dto between /team/settings and /contact

- checker/check.go
If trigger check fails, log event should have warning level instead of error.
> fix(checker): change log to warning if remote unavailable

- cmd/api/config.go
- cmd/api/config_test.go
- cmd/checker/config.go
- cmd/cli/config.go
- cmd/config.go
- cmd/filter/config.go
- cmd/notifier/config.go
- database/redis/config.go
- database/redis/database.go
Pass configuration for connection pool in go-redis to moira database configs
> feat: Pass redis connection pool settings to config

- api/dto/triggers.go
- api/handler/trigger.go
- api/handler/triggers.go
Make function `PopulatedDescription` non mutating and hoist assignment of populated description to handlers
> bugfix: Populating trigger description when creating trigger

- api/handler/trigger.go
- api/handler/triggers.go
Может вернуть как обычная ошибка, так и 400 с описанием дерева проблем, если был использовал флаг `?validate=true`. `openapi 2.0` не поддерживает `oneOf` в параметрах типа, так что лучшее, что мы можем сделать — обобщить тип до `interface{}`
[ПР в client-go](https://github.com/moira-alert/client-go/pull/14)
> fix(swagger): Change body type to any in trigger create and update spec

- senders/webhook/webhook.go
- senders/webhook/webhook_test.go
Add `insecure_tls` option for webhook sender (same as for mattermost sender)
> feat: insecure tls option for webhook

- api/authorization.go
- api/handler/config.go
- api/handler/trigger.go
- api/handler/triggers_test.go
- cmd/api/config.go
- cmd/api/config_test.go
- cmd/api/main.go
If we added by list username or service-login, triggers, that be created by these login can be deleted only by admins or this person.
> feat(api): Add ability filer who can delete triggers

- notifier/selfstate/selfstate_test.go
- senders/selfstate/selfstate.go
- senders/selfstate/selfstate_test.go
- state.go
Selfstate sender should disable notifier as AUTO actor with MANUAL rights.
> fix: selfstate sender disables as dedicated actor

- senders/webhook/payload.go
Change webhook type from `String` to  `moira.State`
> fix: change webhook type string -> moira.State
